title: ArcSmith Docs
description: "Documentação do ArcSmith publicada com GitHub Pages e Jekyll."
baseurl: "/Arc.Smith"
url: "https://yan-azevedo.github.io"
theme: jekyll-theme-cayman

markdown: kramdown
